// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcoq6hOHbAHYxt_LINI2k0niYbZ797vOQ',
    appId: '1:540379093695:web:14388decba56093c08440a',
    messagingSenderId: '540379093695',
    projectId: 'mau-friend-new',
    authDomain: 'mau-friend-new.firebaseapp.com',
    storageBucket: 'mau-friend-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvSSDDGO6-Qw_JRaQr7KXp6_pkowSsyiQ',
    appId: '1:540379093695:android:ae371e660fdb7c0708440a',
    messagingSenderId: '540379093695',
    projectId: 'mau-friend-new',
    storageBucket: 'mau-friend-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN18aEJ7oppOeoYiL3-KUl8QVevgpJBcQ',
    appId: '1:540379093695:ios:c5a0126d828def1808440a',
    messagingSenderId: '540379093695',
    projectId: 'mau-friend-new',
    storageBucket: 'mau-friend-new.firebasestorage.app',
    iosBundleId: 'com.example.mauFriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN18aEJ7oppOeoYiL3-KUl8QVevgpJBcQ',
    appId: '1:540379093695:ios:c5a0126d828def1808440a',
    messagingSenderId: '540379093695',
    projectId: 'mau-friend-new',
    storageBucket: 'mau-friend-new.firebasestorage.app',
    iosBundleId: 'com.example.mauFriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcoq6hOHbAHYxt_LINI2k0niYbZ797vOQ',
    appId: '1:540379093695:web:5ea2480d36d4c51908440a',
    messagingSenderId: '540379093695',
    projectId: 'mau-friend-new',
    authDomain: 'mau-friend-new.firebaseapp.com',
    storageBucket: 'mau-friend-new.firebasestorage.app',
  );

}